module3-task1 - add routing and refactoring
htmlacademy-react/1849247-what-to-watch-11 pull request #4
Opened 2022-10-30 19:28 UTC by rmfomin

2022-10-30 19:39 UTC, knenkne requested changes

2022-10-30 19:39 UTC, knenkne commented on .prettierrc
> +{
Нужно добавить в `.gitignore`

2022-10-30 19:39 UTC, knenkne commented on project/src/components/app/app.tsx
> +            2. в enum нет слеша / - как сохранить единообразие?
```jsx
path={`${AppRoute.Films}/:id`}
```

2022-10-30 19:39 UTC, knenkne commented on project/src/components/app/app.tsx
> +            1. Ошибка - You provided a `checked` prop to a form field without an `onChange` handler.
Пока можно забить

2022-10-30 19:39 UTC, knenkne commented on project/src/components/app/app.tsx
> +        </Route>
Лучше объединить это в один `Route`, как я показал выше, т.к страницы без `id` быть не может

2022-10-30 19:39 UTC, knenkne commented on project/src/components/private-route/private-route.tsx
> +      ? children as JSX.Element // Просто children вызывает ошибку. Пока написал children as JSX.Element. TODO: Почему?
```jsx
type PrivatRouteProps = {
  authorizationStatus: AuthorizationStatus;
  children: JSX.Element;
};
```

2022-10-30 19:39 UTC, knenkne commented on project/src/pages/main-page/main-page.tsx
> +              <FilmCard key={Math.floor(Math.random() * (1000 - 1 + 1)) + 1} />
Ключи могут совпасть 😃 Если хочешь правильно, то делай через `uuidv4`

2022-10-31 06:53 UTC, rmfomin commented on project/src/components/private-route/private-route.tsx
> +      ? children as JSX.Element // Просто children вызывает ошибку. Пока написал children as JSX.Element. TODO: Почему?
Но я же задаю тип 
`{ authorizationStatus, children }: React.PropsWithChildren<PrivateRouteProps>`,
то есть ожидаю что children у меня будут и так затипизированы с помощью PropsWithChildren.
Иначе можно было бы написать просто как
`{ authorizationStatus, children }: PrivatRouteProps`

2022-10-31 08:45 UTC, knenkne commented on project/src/components/private-route/private-route.tsx
> +      ? children as JSX.Element // Просто children вызывает ошибку. Пока написал children as JSX.Element. TODO: Почему?
> Но я же задаю тип `{ authorizationStatus, children }: React.PropsWithChildren<PrivateRouteProps>`, то есть ожидаю что children у меня будут и так затипизированы с помощью PropsWithChildren. Иначе можно было бы написать просто как `{ authorizationStatus, children }: PrivatRouteProps`

Трудно сказать, не зная точной ошибки. [Тут ](https://codesandbox.io/s/propswithchildren-3scmd)можно различные примеры по работе с `children` посмотреть

2022-10-31 19:00 UTC, merged